<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $iduser
 * @property string $create_date
 * @property string $update_date
 * @property string $name
 * @property string $gender
 * @property string $birth_date
 * @property string $email
 * @property string $fone
 * @property string $login
 * @property string $password
 *
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'create_date';
	}

	public function rules() {
		return array(
			array('create_date, update_date, name, gender, birth_date, email, fone, login, password', 'required'),
			array('name, email', 'length', 'max'=>130),
			array('gender', 'length', 'max'=>1),
			array('fone', 'length', 'max'=>11),
			array('login, password', 'length', 'max'=>45),
			array('iduser, create_date, update_date, name, gender, birth_date, email, fone, login, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iduser' => Yii::t('app', 'Iduser'),
			'create_date' => Yii::t('app', 'Create Date'),
			'update_date' => Yii::t('app', 'Update Date'),
			'name' => Yii::t('app', 'Name'),
			'gender' => Yii::t('app', 'Gender'),
			'birth_date' => Yii::t('app', 'Birth Date'),
			'email' => Yii::t('app', 'Email'),
			'fone' => Yii::t('app', 'Fone'),
			'login' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Password'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('birth_date', $this->birth_date, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('fone', $this->fone, true);
		$criteria->compare('login', $this->login, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}