<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property integer $iduser
 * @property string $create_date
 * @property string $update_date
 * @property string $name
 * @property string $gender
 * @property string $birth_date
 * @property string $email
 * @property string $ddd
 * @property string $fone
 * @property string $username
 * @property string $password
 *
 * @property Task[] $tasks
 */
abstract class BaseUser extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Usuário|Usuários', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, gender, birth_date, email, ddd, fone, username, password', 'required'),
			array('name, email', 'length', 'max'=>130),
			array('gender', 'length', 'max'=>1),
			array('ddd', 'length', 'max'=>4),
			array('fone', 'length', 'max'=>11),
			array('username, password', 'length', 'max'=>45),
			array('create_date, update_date', 'safe'),
			array('create_date, update_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('iduser, create_date, update_date, name, gender, birth_date, email, ddd, fone, username, password', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tasks' => array(self::HAS_MANY, 'Task', 'iduser_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'iduser' => Yii::t('app', 'Código'),
			'create_date' => Yii::t('app', 'Data do cadastro'),
			'update_date' => Yii::t('app', 'Data da última edição'),
			'name' => Yii::t('app', 'Nome'),
			'gender' => Yii::t('app', 'Gênero'),
			'birth_date' => Yii::t('app', 'Data de nascimento'),
			'email' => Yii::t('app', 'Email'),
			'ddd' => Yii::t('app', 'Ddd'),
			'fone' => Yii::t('app', 'Telefone'),
			'username' => Yii::t('app', 'Login'),
			'password' => Yii::t('app', 'Senha'),
			'tasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('iduser', $this->iduser);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('birth_date', $this->birth_date, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('ddd', $this->ddd, true);
		$criteria->compare('fone', $this->fone, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}