<?php

/**
 * This is the model base class for the table "task".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Task".
 *
 * Columns in table "task" available as properties of the model,
 * followed by relations of table "task" available as properties of the model.
 *
 * @property integer $idtask
 * @property string $create_date
 * @property string $update_date
 * @property string $title
 * @property integer $iduser_fk
 * @property string $privacy
 * @property string $description
 * @property integer $idtasktype_fk
 * @property string $status
 * @property string $conclusion_date
 *
 * @property Tasktype $idtasktypeFk
 * @property User $iduserFk
 */
abstract class BaseTask extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'task';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Tarefa|Tarefas', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, privacy, description, idtasktype_fk, status', 'required'),
			array('iduser_fk, idtasktype_fk', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>130),
			array('privacy, status', 'length', 'max'=>1),
			array('create_date, update_date, conclusion_date', 'safe'),
			array('create_date, update_date, iduser_fk, conclusion_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('idtask, create_date, update_date, title, iduser_fk, privacy, description, idtasktype_fk, status, conclusion_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idtasktypeFk' => array(self::BELONGS_TO, 'Tasktype', 'idtasktype_fk'),
			'iduserFk' => array(self::BELONGS_TO, 'User', 'iduser_fk'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'idtask' => Yii::t('app', 'Código'),
			'create_date' => Yii::t('app', 'Data do cadastro'),
			'update_date' => Yii::t('app', 'Data da última edição'),
			'title' => Yii::t('app', 'Título'),
			'iduser_fk' => null,
			'privacy' => Yii::t('app', 'Privacidade'),
			'description' => Yii::t('app', 'Descrição'),
			'idtasktype_fk' => null,
			'status' => Yii::t('app', 'Status'),
			'conclusion_date' => Yii::t('app', 'Data de conclusão'),
			'idtasktypeFk' => null,
			'iduserFk' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('idtask', $this->idtask);
		$criteria->compare('create_date', $this->create_date, true);
		$criteria->compare('update_date', $this->update_date, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('iduser_fk', Yii::app()->user->id);
		$criteria->compare('privacy', $this->privacy, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('idtasktype_fk', $this->idtasktype_fk);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('conclusion_date', $this->conclusion_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}